### ISSUE TITLE
Add option to install `mujoco` from source

### ISSUE THREAD

**Issue by alberthli** [Caltech-AMBER/ambersim#10]
Requested by @kli58. Allows pulling the most recent changes in between releases. Also change the default solver to `NEWTON` in `load_mj_model_from_file` after fixing.

**Comment by vincekurtz** [comment]
Also seems pretty essential given that MJX v3.0.0 has a nasty bug with models with one actuator: https://github.com/google-deepmind/mujoco/issues/1135

**Comment by alberthli** [comment]
I'm working on correctly parsing URDFs right now by writing our own in-house util. Would you be interested in picking this up?

The main work here is figuring out how to cleanly edit the `pyproject.toml` so that we have a choice between the `pypi` release and some pinned github commit (or whatever is just on there most recently on `main`). I couldn't immediately figure out how to both give a choice and install the `pypi` one by default - it's easy to just make two different dependency groups that are optional, though.

**Comment by vincekurtz** [comment]
Per f2f, we'll try to see if it's possible to install the latest MJX without completely rebuilding mujoco C++
