### ISSUE TITLE
Save and load policies from a file

### ISSUE THREAD

**Issue by vincekurtz** [Caltech-AMBER/ambersim#29]
The [MJX tutorial](https://colab.research.google.com/github/google-deepmind/mujoco/blob/main/mjx/tutorial.ipynb) has a partial example, but it's incomplete, as it relies on a `make_inference_fn` that was created during training and never saved. We should have some utilities to make saving and loading easy, particularly for non-default policy architectures.

**Comment by alberthli** [comment]
Whoever picks this up should start from here: https://flax.readthedocs.io/en/latest/api_reference/flax.serialization.html
